name: Backend CD

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: myusername/spring-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3

      - name: Gradle 캐시
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: 스프링부트 애플리케이션 빌드
        run: ./gradlew build -x test

      - name: 도커 이미지 빌드
        run: docker build -t yangwoohyeon/my-web .

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub 퍼블리시
        run: push yangwoohyeon/my-web

      - name: EC2 인스턴스 접속 및 애플리케이션 실행
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop spring-app || true
            docker rm spring-app || true
            docker pull yangwoohyeon/my-web
            docker run -d -p 8080:8080 --name spring-app yangwoohyeon/my-web
